[TextureOverride1]
hash = 52df9651
this = Resource1
[Resource1]
filename = Ramen.dds

[TextureOverride2]
hash = d8117661
this = Resource2
[Resource2]
filename = ChopDude.dds
; shader
[ShaderOverrideTexture2]
hash = be12a5f4ac10dbf5
allow_duplicate_hash = true
checktextureoverride = ps-t3
;ps-t3 = Resource2

[TextureOverride3]
hash = 5f4d860d
this = Resource3
[Resource3]
filename = Board.dds

[TextureOverride4]
hash = 03afca59
this = Resource4
[Resource4]
filename = Wave.dds

[TextureOverride5]
hash = 2b399338
this = Resource5
[Resource5]
filename = Walls.dds

[TextureOverride6]
hash = 0f1f035f
this = Resource6
[Resource6]
filename = Attract.dds
; shader
[ShaderOverrideTexture6]
hash = 3705b4171f9856fa
allow_duplicate_hash = true
checktextureoverride = ps-t3
