[TextureOverride1]
hash = dbabdd24
this = Resource1
[Resource1]
filename = Workbench.dds
; shader
	[ShaderOverrideTexture1]
hash = ad7cfb6be22340c6
allow_duplicate_hash = true
checktextureoverride = ps-t10

[TextureOverride2]
hash = afaa88bf
this = Resource2
[Resource2]
filename = Misc1.dds

[TextureOverride3]
hash = 97a4cd53
this = Resource3
[Resource3]
filename = Cards.dds

[TextureOverride4]
hash = 90c178a7
this = Resource4
[Resource4]
filename = HddTarget.dds
