[TextureOverride1]
hash = dbabdd24
this = Resource1
[Resource1]
filename = Workbench.dds
; shader
	[ShaderOverrideTexture1]
hash = ad7cfb6be22340c6
allow_duplicate_hash = true
checktextureoverride = ps-t10
