[TextureOverride1]
hash = 0a3518c7
this = Resource1
[Resource1]
filename = ScrollingZZZ.dds
; shader
[ShaderOverride1]
hash = 5eaff20cf9163893
allow_duplicate_hash = true
checktextureoverride = ps-t1

[TextureOverride2]
hash = 1bc5b817
this = Resource2
[Resource2]
filename = Misc.dds

[TextureOverride3]
hash = 5d3cc4df
this = Resource3
[Resource3]
filename = Roles.dds

[TextureOverride4]
hash = 50ee8384
this = Resource4
[Resource4]
filename = Tape.dds

[TextureOverride5]
hash = 80ab7527
this = Resource5
[Resource5]
filename = ScrollingZZZSmall.dds

[TextureOverride6]
hash = 2621f8f0
this = Resource6
[Resource6]
filename = Attributes.dds

[TextureOverride7]
hash = 73072ecd
this = Resource7
[Resource7]
filename = Master.dds

[TextureOverride8]
hash = 87821dae
this = Resource8
[Resource8]
filename = Star.dds

[TextureOverride9]
hash = 83365bb7
this = Resource9
[Resource9]
filename = Rank.dds

[TextureOverride10]
hash = c0220d03
this = Resource10
[Resource10]
filename = CharaRank.dds

[TextureOverride11]
hash = f65367b3
this = Resource11
[Resource11]
filename = Cinema.dds

























