[TextureOverride1]
hash = 36533c12
this = Resource1
[Resource1]
filename = MainHDD.dds
; shader
	[ShaderOverrideTexture1]
hash = ad7cfb6be22340c6
allow_duplicate_hash = true
checktextureoverride = ps-t10

[TextureOverride2]
hash = 374b2676
this = Resource2
[Resource2]
filename = SubPrograming.dds

[TextureOverride3]
hash = 6ca5377f
this = Resource3
[Resource3]
filename = BigStatic.dds

[TextureOverride4]
hash = aa142c3f
this = Resource4
[Resource4]
filename = Fax.dds

[TextureOverride5]
hash = 9381e329
this = Resource5
[Resource5]
filename = SubHDD.dds

[TextureOverride6]
hash = 7e6c9f73
this = Resource6
[Resource6]
filename = SubStatic.dds

[TextureOverride7]
hash = 31891a18
this = Resource7
[Resource7]
filename = SubTvBackground.dds 
	[ShaderOverrideTexture7]
hash = ad7cfb6be22340c6
allow_duplicate_hash = true
checktextureoverride = ps-t12

[TextureOverride8]
hash = 6496fd89
this = Resource8
[Resource8]
filename = SubStatic2.dds 

[TextureOverride9]
hash = db8b04f1
this = Resource9
[Resource9]
filename = SubHDDScroll.dds 

[TextureOverride10]
hash = 2833a896
this = Resource10
[Resource10]
filename = SubTvBackground2.dds 

[TextureOverride11]
hash = 1f2a4413
this = Resource11
[Resource11]
filename = SubRainbow.dds 

[TextureOverride12]
hash = 04027835
this = Resource12
[Resource12]
filename = Sonar.dds 

[TextureOverride13]
hash = 6568659b
this = Resource13
[Resource13]
filename = Laptop.dds 


































