[TextureOverride1]
hash = 36533c12
this = Resource1
[Resource1]
filename = MainHDD.dds
; shader
	[ShaderOverrideTexture1]
hash = ad7cfb6be22340c6
allow_duplicate_hash = true
checktextureoverride = ps-t10