; --- Texture Override ---

[TextureOverrideWiseBedroomPosters]
hash = 89e5e72e
match_priority = 69069
this = ResourceWiseBedroomPosters

; --- Shader Override ---

; --- Resources ---

[ResourceWiseBedroomPosters]
filename = wiseBedroomPosters.dds