; --- Texture Override ---

[TextureOverrideBigPoster]
hash = 4596b831
match_priority = 777
this = ResourceBiggiePost
run = commandListSkinTexture

[TextureOverrideBigPosterDiffuse]
hash = 03e4c5ee
this = ResourceRoughness

; --- Shader Override ---

; --- Resources ---

[ResourceBiggiePost]
filename = bigPoster.dds

[ResourceRoughness]
filename = roughness.dds