[TextureOverride1]
hash = f021ae71
this = Resource1
[Resource1]
filename = LogoStand.dds

[TextureOverride2]
hash = 3a442fda
this = Resource2
[Resource2]
filename = Stand.dds

[TextureOverride3]
hash = 39504c7c
this = Resource3
[Resource3]
filename = Glass.dds
; shader
[ShaderOverrideTexture3]
hash = 14a958f5ff54294d
allow_duplicate_hash = true
checktextureoverride = ps-t10

[TextureOverride4]
hash = 68c26a18
this = Resource4
[Resource4]
filename = Building.dds