[TextureOverride1]
hash = 1d73bba7
this = Resource1
[Resource1]
filename = 1.dds

[TextureOverride2]
hash = 8cb62d30
this = Resource2
[Resource2]
filename = 2.dds

[TextureOverride3]
hash = 69616eca
this = Resource3
[Resource3]
filename = 3.dds

[TextureOverride4]
hash = 9405989d
this = Resource4
[Resource4]
filename = 4.dds

[TextureOverride5]
hash = aac960ee
this = Resource5
[Resource5]
filename = 5.dds

[TextureOverride6]
hash = d04a6584
this = Resource6
[Resource6]
filename = 6.dds

[TextureOverride7]
hash = d66d304d
this = Resource7
[Resource7]
filename = 7.dds

[TextureOverride8]
hash = e361752a
this = Resource8
[Resource8]
filename = 8.dds

[TextureOverrideNine]
hash = 3ca81b0d
this = ResourceNine
[ResourceNine]
filename = 9.dds

[TextureOverride0xA]
hash = 31b0ee4f
this = Resource0xA
[Resource0xA]
filename = 0xA.dds

[TextureOverride0xB]
hash = eea13a17
this = Resource0xB
[Resource0xB]
filename = 0xB.dds
; shaders
[ShaderOverrideTexture0xB]
hash = 9a7dda9683c97bed
allow_duplicate_hash = true
checktextureoverride = ps-t8



[TextureOverride0xC]
hash = 6862b57a
this = Resource0xC
[Resource0xC]
filename = 0xC.dds

[TextureOverride0xD]
hash = ab3542d2
this = Resource0xD
[Resource0xD]
filename = 0xD.dds
; shaders
[ShaderOverrideTexture0xD]
hash = 3ac77b4becc4e4e3
allow_duplicate_hash = true
checktextureoverride = ps-t6

[TextureOverride0xE]
hash = 677af421
this = Resource0xE
[Resource0xE]
filename = 0xE.dds

[TextureOverride0xF]
hash = 568ad96e
this = Resource0xF
[Resource0xF]
filename = 0xF.dds

: 

[TextureOverride9]
hash = a9328ab9
this = Resource9
[Resource9]
filename = Dream.dds

[TextureOverride10]
hash = 6f0eca58
this = Resource10
[Resource10]
filename = Ninja.dds

[TextureOverride11]
hash = 27e401d8
this = Resource11
[Resource11]
filename = Boo1.dds

[TextureOverride12]
hash = 28ee3732
this = Resource12
[Resource12]
filename = SRank.dds

[TextureOverride13]
hash = 38da69be
this = Resource13
[Resource13]
filename = ARank.dds

[TextureOverride14]
hash = 912dc126
this = Resource14
[Resource14]
filename = Boo2.dds

[TextureOverride15]
hash = d8faece7
this = Resource15
[Resource15]
filename = BRank.dds
; shaders
[ShaderOverrideTexture15]
hash = 23397490833b2771
allow_duplicate_hash = true
checktextureoverride = ps-t8

[TextureOverride16]
hash = dd2c4ba1
this = Resource16
[Resource16]
filename = Engine.dds

[TextureOverride17]
hash = 4446ddc3
this = Resource17
[Resource17]
filename = TVs.dds

[TextureOverride18]
hash = 94f92326
this = Resource18
[Resource18]
filename = Rex.dds

[TextureOverride19]
hash = 6c7df986
this = Resource19
[Resource19]
filename = Rex2.dds

[TextureOverride20]
hash = cc1c75ca
this = Resource20
[Resource20]
filename = 20.dds

[TextureOverride21]
hash = 5d69619a
this = Resource21
[Resource21]
filename = 21.dds

[TextureOverride22]
hash = 5c821e4d
this = Resource22
[Resource22]
filename = 22.dds

[TextureOverride23]
hash = eb022b51
this = Resource23
[Resource23]
filename = 23.dds

[TextureOverride24]
hash = d277ea75
this = Resource24
[Resource24]
filename = 24.dds

[TextureOverride25]
hash = 7d9ce9bd
this = Resource25
[Resource25]
filename = 25.dds

[TextureOverride26]
hash = 3ec7a745
this = Resource26
[Resource26]
filename = Engine2.dds

[TextureOverride27]
hash = 510d8187
this = Resource27
[Resource27]
filename = BooChoco.dds

[TextureOverride28]
hash = fa7193fb
this = Resource28
[Resource28]
filename = Ramen.dds

[TextureOverride29]
hash = ebbe2741
this = Resource29
[Resource29]
filename = Camera.dds

[TextureOverride30]
hash = 4378fe42
this = Resource30
[Resource30]
filename = Soda.dds

[TextureOverride31]
hash = 197dbdec
this = Resource31
[Resource31]
filename = IceCream.dds

[TextureOverride32]
hash = 64af9d27
this = Resource32
[Resource32]
filename = Camera2.dds

[TextureOverride33]
hash = f9fc2405
this = Resource33
[Resource33]
filename = Meat.dds

[TextureOverride34]
hash = 72807698
this = Resource34
[Resource34]
filename = Paradise.dds

[TextureOverride35]
hash = 8301941e
this = Resource35
[Resource35]
filename = Drink.dds

[TextureOverride36]
hash = 353456ef
this = Resource36
[Resource36]
filename = Boo3.dds

[TextureOverride37]
hash = 82c56f58
this = Resource37
[Resource37]
filename = Text.dds

[TextureOverride38]
hash = 1eb0037a
this = Resource38
[Resource38]
filename = Drink2.dds

[TextureOverride39]
hash = f09f71a1
this = Resource39
[Resource39]
filename = Star.dds

[TextureOverride40]
hash = ec54d0b5
this = Resource40
[Resource40]
filename = Sandwich.dds

[TextureOverride41]
hash = 614ff055
this = Resource41
[Resource41]
filename = Drink3.dds










































