[TextureOverride1]
hash = 4f92b040
this = Resource1
[Resource1]
filename = Slippery.dds

[TextureOverride2]
hash = 6e730663
this = Resource2
[Resource2]
filename = Attract.dds
; shader
[ShaderOverrideTexture2]
hash = b8b97eab97c48273
allow_duplicate_hash = true
checktextureoverride = ps-t6

; ------------ Screen
[TextureOverride3]
hash = 33a61783
this = Resource3
[Resource3]
filename = ScreenRiot.dds

[TextureOverride4]
hash = edb20ed9
this = Resource4
[Resource4]
filename = ScreenKungFu.dds

[TextureOverride5]
hash = 15e1b6fd
this = Resource5
[Resource5]
filename = ScreenOctopus.dds

[TextureOverride6]
hash = 2df97fa5
this = Resource6
[Resource6]
filename = ScreenBull.dds

; ------------ Screen Shaders
[ShaderOverrideTexture3]
hash = d0675a622e47edf2
allow_duplicate_hash = true
checktextureoverride = ps-t5
; --------------

[TextureOverride7]
hash = 53764668
this = Resource7
[Resource7]
filename = Arcade.dds
[ShaderOverrideTexture7]
hash = 1db47003729b2c84
allow_duplicate_hash = true
checktextureoverride = ps-t2

[TextureOverride8]
hash = a4bff879
this = Resource8
[Resource8]
filename = Para.dds













