; === Main Posters ===
; --- Texture Override ---

[TextureOverrideMainPosters]
hash = 9c199f0a
match_priority = 69420
this = ResourceMainPosters

[TextureOverrideMainPostersMed]
hash = 5b6c7ea6
match_priority = 69419
this = ResourceMainPosters

[TextureOverrideMainPostersFarProbably]
hash = 0277445e
match_priority = 69419
this = ResourceMainPosters

; --- Shader Override ---

[ShaderOverridePostersDay]
hash = 06b02530549b1627
allow_duplicate_hash = true
checktextureoverride = ps-t2

[ShaderOverridePostersNight]
hash = ae7d9337da303176
allow_duplicate_hash = true
checktextureoverride = ps-t5

; --- Resources ---

[ResourceMainPosters]
filename = mainPosters.dds

; --- Others
[TextureOverride1]
hash = cda8e901
this = Resource1
[Resource1]
filename = RecomendationShelve.dds

[TextureOverride2]
hash = 00dc37b0
this = Resource2
[Resource2]
filename = Skateboard.dds
; shader
[ShaderOverrideTexture2]
hash = 1db47003729b2c84
allow_duplicate_hash = true
checktextureoverride = ps-t2

[TextureOverride3]
hash = 870c54f7
this = Resource3
[Resource3]
filename = RandomItems.dds

[TextureOverride4]
hash = e1d11da9
this = Resource4
[Resource4]
filename = Cushion.dds

















