; === Main Posters ===
; --- Texture Override ---

[TextureOverrideMainPosters]
hash = 9c199f0a
match_priority = 69420
this = ResourceMainPosters

[TextureOverrideMainPostersMed]
hash = 5b6c7ea6
match_priority = 69419
this = ResourceMainPosters

[TextureOverrideMainPostersFarProbably]
hash = 0277445e
match_priority = 69419
this = ResourceMainPosters

; --- Shader Override ---

[ShaderOverridePostersDay]
hash = 06b02530549b1627
allow_duplicate_hash = true
checktextureoverride = ps-t2

[ShaderOverridePostersNight]
hash = ae7d9337da303176
allow_duplicate_hash = true
checktextureoverride = ps-t5

; --- Resources ---

[ResourceMainPosters]
filename = mainPosters.dds

; --- Others
[TextureOverride1]
hash = cda8e901
this = Resource1
[Resource1]
filename = RecomendationShelve.dds

[TextureOverride2]
hash = 00dc37b0
this = Resource2
[Resource2]
filename = Skateboard.dds
; shader
[ShaderOverrideTexture2]
hash = 1db47003729b2c84
allow_duplicate_hash = true
checktextureoverride = ps-t2

[TextureOverride3]
hash = 870c54f7
this = Resource3
[Resource3]
filename = RandomItems.dds

[TextureOverride4]
hash = e1d11da9
this = Resource4
[Resource4]
filename = Cushion.dds

[TextureOverride6]
hash = 0508f06c
this = Resource6
[Resource6]
filename = Shelve.dds

[TextureOverride7]
hash = d8de3adf
this = Resource7
[Resource7]
filename = Tapes.dds





[TextureOverride5]
hash = 3d02454a
this = Resource5
[Resource5]
filename = TV.dds
; time of day shaders
	[ShaderOverrideTexture41]
hash = 3612906e1d615dda
allow_duplicate_hash = true
checktextureoverride = ps-t10
	[ShaderOverrideTexture42]
hash = daebc523409a822b
allow_duplicate_hash = true
checktextureoverride = ps-t10
	[ShaderOverrideTexture43]
hash = 4628e1a3a9df9736
allow_duplicate_hash = true
checktextureoverride = ps-t10
	[ShaderOverrideTexture44]
hash = 130d4783d644e8e9
allow_duplicate_hash = true
checktextureoverride = ps-t10
	[ShaderOverrideTexture45]
hash = 2cad314f6814ccdf
allow_duplicate_hash = true
checktextureoverride = ps-t10
	[ShaderOverrideTexture46]
hash = 0d067bd78581fd17
allow_duplicate_hash = true
checktextureoverride = ps-t10
	[ShaderOverrideTexture47]
hash = 061e76862bcc176a
allow_duplicate_hash = true
checktextureoverride = ps-t10
	[ShaderOverrideTexture48]
hash = 3ec4aa86d2b902d7
allow_duplicate_hash = true
checktextureoverride = ps-t10
	[ShaderOverrideTexture49]
hash = fa9eabf4c04fa18a
allow_duplicate_hash = true
checktextureoverride = ps-t10
	[ShaderOverrideTexture410]
hash = 3ec4aa86d2b902d7
allow_duplicate_hash = true
checktextureoverride = ps-t10
	[ShaderOverrideTexture411]
hash = 4628e1a3a9df9736
allow_duplicate_hash = true
checktextureoverride = ps-t10
	[ShaderOverrideTexture412]
hash = ea5fefc68438b0e6
allow_duplicate_hash = true
checktextureoverride = ps-t10
	[ShaderOverrideTexture413]
hash = d218c8207c14aaaf
allow_duplicate_hash = true
checktextureoverride = ps-t10
	[ShaderOverrideTexture414]
hash = 49b10599d4292d0b
allow_duplicate_hash = true
checktextureoverride = ps-t10
	[ShaderOverrideTexture415]
hash = e6e7546bfbd3d177
allow_duplicate_hash = true
checktextureoverride = ps-t10






















