; These shaders manages most textures
; Their hashs change most patch

[ShaderOverrideTextureGeneral]
hash = efeff000896b0536
allow_duplicate_hash = true
checktextureoverride = ps-t2

[ShaderOverrideTextureRoad]
hash = 1ef1eb5c1e03d1ba
allow_duplicate_hash = true
checktextureoverride = ps-t1

[ShaderOverrideTextureScreens]
hash = d1ba766a0c8341cb
allow_duplicate_hash = true
checktextureoverride = ps-t5

[ShaderOverrideTextureBus]
hash = d1ba766a0c8341cb
allow_duplicate_hash = true
checktextureoverride = ps-t2

[ShaderOverrideTextureGraffiti]
hash = 6af7573b719cfbfb
allow_duplicate_hash = true
checktextureoverride = ps-t1

; Random Play TVs
[TextureOverride2]
hash = 3d02454a
this = ResourceVideoStoreVitrine
[ResourceVideoStoreVitrine]
filename = TVs.dds
; OUTDOOR
[ShaderOverrideTextureVideoStoreVitrineClose]
hash = a7a83d1b82f98842
allow_duplicate_hash = true
ps-t5 = ResourceVideoStoreVitrine
[ShaderOverrideTextureVideoStoreVitrineFar]
hash = 8bf9f814eddcd2cb
allow_duplicate_hash = true
ps-t6 = ResourceVideoStoreVitrine
; BELLE ROOM
[ShaderOverrideTextureBellRoomScreens]
hash = f082427a339b9f9e
allow_duplicate_hash = true
checktextureoverride = ps-t10

[ShaderOverrideTextureArcadeAttract]
hash = 9d609e731dc6def6
allow_duplicate_hash = true
checktextureoverride = ps-t6

[ShaderOverrideTextureRamenAttract]
hash = 657f649f3d432877
allow_duplicate_hash = true
checktextureoverride = ps-t3

[ShaderOverrideTextureCoffeePoster]
hash = 71ca66614965ca53
allow_duplicate_hash = true
checktextureoverride = ps-t2

[ShaderOverrideTextureCoffeeGlass]
hash = d929c1f85d6ba4ef
allow_duplicate_hash = true
checktextureoverride = ps-t10

[ShaderOverrideTextureLoadingScreenPosters]
hash = 1d547229ba667e8d
allow_duplicate_hash = true
checktextureoverride = ps-t2

[ShaderOverrideTextureStaffScreens]
hash = 3f0b4a9d596a2c64
allow_duplicate_hash = true
checktextureoverride = ps-t10

[ShaderOverrideTextureBelleWatermelon]
hash = ca2b07c426cc7263
allow_duplicate_hash = true
checktextureoverride = ps-t13

















