[TextureOverride6]
hash = 2d7fc24a
this = Resource6
[Resource6]
filename = Boo.dds
; shader
[ShaderOverrideTexture6]
hash = 857cd16250c6142e
allow_duplicate_hash = true
checktextureoverride = ps-t0

[TextureOverride1]
hash = d4377054
this = Resource1
[Resource1]
filename = NowLoading.dds