[TextureOverride1]
hash = 4ba8c3eb
this = Resource1
[Resource1]
filename = TrafficSign.dds

[TextureOverride2]
hash = 778b663f
this = Resource2
[TextureOverride2Far]
hash = 1c6230d9
this = Resource2
[Resource2]
filename = Security.dds

[TextureOverride3]
hash = d69d6e8e
this = Resource3
[TextureOverride3Far]
hash = 18c3ba07
this = Resource3
[Resource3]
filename = Vending.dds

[TextureOverride4]
hash = b72ee339
this = Resource4
[TextureOverride4Far]
hash = 98453181
this = Resource4
[Resource4]
filename = Parking.dds

[TextureOverride5]
hash = 8cce9932
this = Resource5
[Resource5]
filename = Papers.dds

[TextureOverride6]
hash = d442e11a
this = Resource6
[Resource6]
filename = SkateBench.dds

[TextureOverride7]
hash = 1cf99d1e
this = Resource7
[Resource7]
filename = Road.dds
; shader
[ShaderOverrideTexture7]
hash = 37f15ecc7643e11b
allow_duplicate_hash = true
checktextureoverride = ps-t1

[TextureOverride8]
hash = d8a0c40a
this = Resource8
[Resource8]
filename = Nuclear.dds

[TextureOverride9]
hash = 7ab24407
this = Resource9
[TextureOverride9Far]
hash = e69f4417
this = Resource9
[Resource9]
filename = SecurityBarrer.dds

[TextureOverride10]
hash = 96b916fb
this = Resource10
[Resource10]
filename = tarpaulin.dds

[TextureOverride11]
hash = 379da554
this = Resource11
[Resource11]
filename = Container.dds

[TextureOverride12]
hash = 37817455
this = Resource12
[Resource12]
filename = Drinks.dds
















