; --- Texture Override ---

[TextureOverrideStaffRoomPosters]
hash = 50719aae
match_priority = 9000
this = ResourceStaffRoomPosters

[TextureOverrideStaffRoomPictures]
hash = 270ccae5
match_priority = 9001
this = ResourceStaffRoomPictures

; --- Shader Override ---

; --- Resources ---

[ResourceStaffRoomPosters]
filename = staffPosters.dds

[ResourceStaffRoomPictures]
filename = staffPictures.dds