[TextureOverride1]
hash = 7e95f6c5
this = Resource1
[Resource1]
filename = Building.dds


; ------ Car
[TextureOverride2]
hash = 0b3e1922
this = Resource2
[Resource2]
filename = PlayCar.dds
; shader

[ShaderOverrideTexture2]
hash = 258854610f9a9f88
allow_duplicate_hash = true
ps-t7 = Resource2

[ShaderOverrideTexture2Far]
hash = e47bbcdc58c402d5
allow_duplicate_hash = true
ps-t6 = Resource2

[ShaderOverrideTexture2Close]
hash = 9e160e68f0166888
allow_duplicate_hash = true
ps-t7 = Resource2
; ------ Car

[TextureOverride3]
hash = 4ea5b579
this = Resource3
[TextureOverride3Far]
hash = 3d3f6047
this = Resource3
[Resource3]
filename = WallTag.dds

[TextureOverride4]
hash = 402c2344
this = Resource4
[Resource4]
filename = Posters.dds

[TextureOverride9]
hash = 4ef5a8c7
this = Resource9
[Resource9]
filename = Juicebox.dds





















