[TextureOverride1]
hash = 0b2c6ca1
this = Resource1
[Resource1]
filename = Fist.dds

[TextureOverride2]
hash = 7a492683
this = Resource2
[Resource2]
filename = FistEffect.dds
; shader
[ShaderOverride1]
hash = e26d8bc83c1ee4eb
allow_duplicate_hash = true
checktextureoverride = ps-t1

[TextureOverride3]
hash = 8b1bb777
this = Resource3
[Resource3]
filename = Arrow.dds

[TextureOverride4]
hash = 45a22755
this = Resource4
[Resource4]
filename = B.dds

[TextureOverride5]
hash = 216d2f47
this = Resource5
[Resource5]
filename = F.dds

[TextureOverride6]
hash = 484b2719
this = Resource6
[Resource6]
filename = E.dds

[TextureOverride7]
hash = 038223d6
this = Resource7
[Resource7]
filename = SpecialEffect.dds

[TextureOverride8]
hash = 107157fa
this = Resource8
[Resource8]
filename = C.dds

[TextureOverride9]
hash = 5223814f
this = Resource9
[Resource9]
filename = AEffect.dds

[TextureOverride10]
hash = 7267510b
this = Resource10
[Resource10]
filename = Assist.dds

[TextureOverride11]
hash = 28881199
this = Resource11
[Resource11]
filename = Wheel.dds

[TextureOverride12]
hash = abb4615f
this = Resource12
[Resource12]
filename = D.dds

[TextureOverride13]
hash = ad5347a7
this = Resource13
[Resource13]
filename = ArrowEffect.dds

[TextureOverride14]
hash = b1bbc42b
this = Resource14
[Resource14]
filename = Special.dds

[TextureOverride15]
hash = b5e77c1f
this = Resource15
[Resource15]
filename = Chain.dds

[TextureOverride16]
hash = d724f203
this = Resource16
[Resource16]
filename = A.dds

[TextureOverride17]
hash = 1ca3f9e6
this = Resource17
[Resource17]
filename = DiscRank.dds












