; --- Texture Override ---

[TextureOverrideMainPosters]
hash = 9c199f0a
match_priority = 69420
this = ResourceMainPosters

[TextureOverrideMainPostersMed]
hash = 5b6c7ea6
match_priority = 69419
this = ResourceMainPosters

[TextureOverrideMainPostersFarProbably]
hash = 0277445e
match_priority = 69419
this = ResourceMainPosters

; --- Shader Override ---

[ShaderOverridePostersDay]
hash = 06b02530549b1627
allow_duplicate_hash = true
checktextureoverride = ps-t2

[ShaderOverridePostersNight]
hash = ae7d9337da303176
allow_duplicate_hash = true
checktextureoverride = ps-t5

; --- Resources ---

[ResourceMainPosters]
filename = mainPosters.dds