; --- Texture Override ---

[TextureOverrideFramedPosters]
hash = a1dd1d84
match_priority = 999
this = ResourceFramedPosters

; --- Shader Override ---

; --- Resources ---

[ResourceFramedPosters]
filename = framedPosters.dds