[TextureOverride1]
hash = 31891a18
this = Resource1
[Resource1]
filename = TvBackground.dds
; shader
[ShaderOverrideTexture1]
hash = aaae3ada3c39df94
allow_duplicate_hash = true
checktextureoverride = ps-t10

; Staff Room's Posters shader
[ShaderOverrideTexture2]
hash = aeab80bc2d5a7de3
allow_duplicate_hash = true
checktextureoverride = ps-t2

[TextureOverride2]
hash = 50477958
this = Resource2
[Resource2]
filename = Tapes.dds
