; [TextureOverride1]
; hash = 766ae6e8
; this = Resource1
; [Resource1]
; filename = Posters.dds
; shader
; [ShaderOverrideTexture1]
; hash = 1db47003729b2c84
; allow_duplicate_hash = true
; checktextureoverride = ps-t2

[TextureOverride1]
hash = ea4d568d
this = Resource1
[Resource1]
filename = Graffiti.dds