; [TextureOverride1]
; hash = 766ae6e8
; this = Resource1
; [Resource1]
; filename = Posters.dds

[TextureOverride1]
hash = ea4d568d
this = Resource1
[Resource1]
filename = Graffiti.dds

[TextureOverride2]
hash = c4854182
this = Resource2
[TextureOverride2Far]
hash = 9834012a
this = Resource2
[Resource2]
filename = UnknowGraffiti.dds

[TextureOverride3]
hash = a0c2b81f
this = Resource3
[Resource3]
filename = Graffiti3.dds

[TextureOverride4]
hash = 158b7296
this = Resource4
[TextureOverride4VeryFar]
hash = 819860b7
this = Resource4
[TextureOverride4Far]
hash = eac29960
this = Resource4
[Resource4]
filename = Big.dds

[TextureOverride5]
hash = dcbc2c19
this = Resource5
[TextureOverride5Far]
hash = 30e52f11
this = Resource5
[TextureOverride5VeryFar]
hash = 6b296d62
this = Resource5
[Resource5]
filename = Tiger.dds
