[TextureOverride1]
hash = 41116a73
this = Resource1
[Resource1]
filename = Products.dds
; shader
[ShaderOverrideTexture1]
hash = 1db47003729b2c84
allow_duplicate_hash = true
checktextureoverride = ps-t2