[TextureOverride1]
hash = 766ae6e8
this = Resource1
[Resource1]
filename = Posters.dds
; shader
[ShaderOverrideTexture1]
hash = 1db47003729b2c84
allow_duplicate_hash = true
checktextureoverride = ps-t2

[TextureOverride2]
hash = 5f1652a1
this = Resource2
[Resource2]
filename = Shelve1.dds
; shader
[ShaderOverrideTexture2]
hash = d0675a622e47edf2
allow_duplicate_hash = true
checktextureoverride = ps-t2


[TextureOverride3]
hash = 0663b9e5
this = Resource3
[Resource3]
filename = Shelve2.dds

[TextureOverride4]
hash = 9d840755
this = Resource4
[Resource4]
filename = Posters2.dds
; shader
[ShaderOverrideTexture4]
hash = 1db47003729b2c84
allow_duplicate_hash = true
checktextureoverride = ps-t2

[TextureOverride5]
hash = 1c02a9d2
this = Resource5
[Resource5]
filename = BirdPoster.dds

[TextureOverride6]
hash = 2c7bbe9f
this = Resource6
[Resource6]
filename = Desk1.dds

[TextureOverride7]
hash = f3fe4b27
this = Resource7
[Resource7]
filename = Stickers.dds
; shader
[ShaderOverrideTexture7]
hash = 32a761e2b53c88c0
allow_duplicate_hash = true
checktextureoverride = ps-t1

[TextureOverride8]
hash = b065dfaa
this = Resource8
[Resource8]
filename = CorkBoard.dds

[TextureOverride9]
hash = 56b86ec2
this = Resource9
[Resource9]
filename = VendingMachines.dds

[TextureOverride10]
hash = 748e2fbb
this = Resource10
[Resource10]
filename = MoreStickers.dds












