[TextureOverride1]
hash = 766ae6e8
this = Resource1
[Resource1]
filename = Posters.dds
; shader
[ShaderOverrideTexture1]
hash = 1db47003729b2c84
allow_duplicate_hash = true
checktextureoverride = ps-t2

[TextureOverride2]
hash = 5f1652a1
this = Resource2
[Resource2]
filename = Shelve1.dds
; shader
[ShaderOverrideTexture2]
hash = d0675a622e47edf2
allow_duplicate_hash = true
checktextureoverride = ps-t2


[TextureOverride3]
hash = 0663b9e5
this = Resource3
[Resource3]
filename = Shelve2.dds

[TextureOverride4]
hash = 9d840755
this = Resource4
[Resource4]
filename = Posters2.dds
; shader
[ShaderOverrideTexture3]
hash = 1db47003729b2c84
allow_duplicate_hash = true
checktextureoverride = ps-t2