; --- Texture Override ---

[TextureOverrideBelleBedroomPostersClose]
hash = 97c36db0
match_priority = 6969
this = ResourceBelleBedroomPosters

[TextureOverrideBelleBedroomPostersMid]
hash = c08520b9
match_priority = 6967
this = ResourceBelleBedroomPosters

; --- Shader Override ---

; --- Resources ---

[ResourceBelleBedroomPosters]
filename = belleBedroomPosters.dds



;
[TextureOverride1]
hash = 3e582aa1
this = Resource1
[Resource1]
filename = TV.dds

[TextureOverride2]
hash = 4a95c0f2
this = Resource2
[Resource2]
filename = TV.dds

[TextureOverride3]
hash = 8a5d0348
this = Resource3
[Resource3]
filename = LaptopScreen.dds

[TextureOverride4]
hash = 8d7509f9
this = Resource4
[Resource4]
filename = Laptop.dds
; shader
[ShaderOverrideTexture4]
hash = ad7cfb6be22340c6
allow_duplicate_hash = true
checktextureoverride = ps-t9

[TextureOverride5]
hash = 446ba349
this = Resource5
[Resource5]
filename = Plates.dds

[TextureOverride6]
hash = c3e964ac
this = Resource6
[Resource6]
filename = DoorFrame.dds

[TextureOverride7]
hash = d348f5e2
this = Resource7
[Resource7]
filename = Skateboards.dds

[TextureOverride8]
hash = 0773b38e
this = Resource8
[Resource8]
filename = Watermelon.dds
; shader
[ShaderOverrideTexture8]
hash = 63302fcf51743086
allow_duplicate_hash = true
checktextureoverride = ps-t13

[TextureOverride9]
hash = 68ee0d5c
this = Resource9
[Resource9]
filename = Ball.dds

[TextureOverride10]
hash = 88c48f3d
this = Resource10
[Resource10]
filename = Pillows.dds

[TextureOverride11]
hash = 1cd17fe1
this = Resource11
[Resource11]
filename = Rug.dds

[TextureOverride12]
hash = 0fb870e1
this = Resource12
[Resource12]
filename = Plates2.dds

[TextureOverride13]
hash = 6e4ef796
this = Resource13
[Resource13]
filename = Bed.dds

[TextureOverride14]
hash = b08d17b8
this = Resource14
[Resource14]
filename = DiscRug.dds


















