; --- Texture Override ---

[TextureOverrideBelleBedroomPostersClose]
hash = 97c36db0
match_priority = 6969
this = ResourceBelleBedroomPosters

[TextureOverrideBelleBedroomPostersMid]
hash = c08520b9
match_priority = 6967
this = ResourceBelleBedroomPosters

; --- Shader Override ---

; --- Resources ---

[ResourceBelleBedroomPosters]
filename = belleBedroomPosters.dds