; Default texture shader (posters)
[ShaderOverrideTexture0]
hash = 1db47003729b2c84
allow_duplicate_hash = true
checktextureoverride = ps-t2

[TextureOverride1]
hash = 7ade02a8
this = Resource1
[Resource1]
filename = Posters.dds
[TextureOverride1Far]
hash = 47b30962
this = Resource1

; ----- TVS 
[Resource2]
filename = TVs.dds

[TextureOverride2]
hash = 3d02454a
this = Resource2
; shader
[ShaderOverrideTexture2]
hash = 4b0ca55e2cae3d44
allow_duplicate_hash = true
ps-t6 = Resource2
; shader
[ShaderOverrideTexture2Close]
hash = 7d74803d13979a65
allow_duplicate_hash = true
ps-t5 = Resource2

; -------

[TextureOverride3]
hash = 7e95f6c5
this = Resource3
[Resource3]
filename = Building.dds

[TextureOverride4]
hash = 32d4bc23
this = Resource4
[Resource4]
filename = DoorStickers.dds
; shader
[ShaderOverrideTexture4]
hash = 1e9ccf2921062b41
allow_duplicate_hash = true
ps-t10 = Resource4

[TextureOverride5]
hash = 9b38f0d0
this = Resource5
[Resource5]
filename = Stickers.dds
[ShaderOverrideTexture5]
hash = 32a761e2b53c88c0
allow_duplicate_hash = true
checktextureoverride = ps-t1


[TextureOverride6]
hash = c117c7ae
this = Resource6
[Resource6]
filename = Vitrine.dds


; -- Records from Bardic Play
[TextureOverride100]
hash = 8fb5b9b7
this = Resource100
[Resource100]
filename = Records.dds
[TextureOverride100Far]
hash = 50e751db
this = Resource100


























[TextureOverride1]
hash = 7ade02a8
this = Resource1
[Resource1]
filename = Posters.dds
[TextureOverride1Far]
hash = 47b30962
this = Resource1

; ----- TVS 
[Resource2]
filename = TVs.dds

[TextureOverride2]
hash = 3d02454a
this = Resource2
; shader
[ShaderOverrideTexture2]
hash = 4b0ca55e2cae3d44
allow_duplicate_hash = true
ps-t6 = Resource2
; shader
[ShaderOverrideTexture2Close]
hash = 7d74803d13979a65
allow_duplicate_hash = true
ps-t5 = Resource2

; -------

[TextureOverride3]
hash = 7e95f6c5
this = Resource3
[Resource3]
filename = Building.dds

[TextureOverride4]
hash = 32d4bc23
this = Resource4
[Resource4]
filename = DoorStickers.dds
; shader
[ShaderOverrideTexture4]
hash = 1e9ccf2921062b41
allow_duplicate_hash = true
ps-t10 = Resource4

[TextureOverride5]
hash = 9b38f0d0
this = Resource5
[Resource5]
filename = Stickers.dds

[TextureOverride6]
hash = c117c7ae
this = Resource6
[Resource6]
filename = Vitrine.dds




























